### PR TITLE
Tips included in documentation.

### PR DESCRIPTION
**Pull request by mira13**
## Requirements

No requirements

## Use case

Beginners start to use eHive and looking for additional info

## Description

Tips added to documentation for optimised usage of eHive
https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-2437

## Possible Drawbacks

no

## Testing

No testing aplicable.

_Have you added/modified unit tests to test the changes?_

_If so, do the tests pass/fail?_

_Have you run the entire test suite and no regression was detected?_

### CODE REVIEW

**Comment by muffato** [comment]
I've enabled this branch on ReadTheDocs but the build fails: https://readthedocs.org/api/v2/build/8866483.txt
I've just triggered another build on master and it failed too (the last build was 2 weeks and 6 days ago, and it had passed): https://readthedocs.org/api/v2/build/8866517.txt
So there is something wrong on RTD which needs to be addressed.

In the meantime, could you build the doc locally and copy it to `~mira/public_html/` ?

**Comment by mira13** [comment]
Now invisible non-ascii symbol removed, build runs fine.

**Comment by muffato** [comment]
Note: rebase once #94 has been merged

**Comment by ens-bwalts** [comment]
Most of this content is copied from tip sheets created by eHive users throughout Ensembl.

**Comment by mira13** [comment]
Actually all content is copied, I have added only markup

**Comment by muffato** [comment]
The fact that all the content comes from users is actually a big warning for me. It's often the case that people misunderstand how eHive works, what it does, and this document could be advocating things that we consider as deprecated or bad practice. The whole content must be properly reviewed, we can't just take it in with some markup.

I haven't yet reviewed the text, yet, but it feels that this document is way too long. The content should in priority be integrated to the main manual, not the Tips page. The Tips page must not have stuff that is not found anywhere else in the manual. The Tips / Cheat-sheet page is intended to be a _short_ document that answers "I'm stuck, please help me !"

**Review by ens-bwalts — APPROVED** [review]

**Comment by ens-bwalts** [comment]
This has been sitting for a while. I think we can go ahead and add it now, and edit as needed in the future

**Review by TamaraNaboulsi — APPROVED** [review]
This definitely needs some fixes added (grammar and spelling mistakes, runWorker.pl instead of run_Worker.pl, ...). It can also benefit from some restructuring as I do agree with what was said before that it's too long for a tips page. Maybe some sections can be smaller and contain links to more detailed explanations in the user manual.

But, as Brandon said, doesn't hurt to add this now as it has been outstanding for a long time, and edits can be added later.

**Pull request merged**
