### PR TITLE
Feature/formatter

### PR DESCRIPTION
**Pull request by mira13**
## Use case

Formatter class added, 
The goal is consistent printing code and output, 
Example of usage is applied for Queen.pm functions called from beekeeper.pl

## Description
Formatter object can be used to set errors, warnings and info print, also it allows to apply custom output functions and set up output format - to json or text, immediate or by demand.

Import the module and use the variable

## Possible Drawbacks

None I can think of

## Testing

_Have you added/modified unit tests to test the changes?_

The test file is added, that covers 100% of formatter code

_Have you run the entire test suite and no regression was detected?_

All fine

### CODE REVIEW

**Comment by mira13** [comment]
@muffato @ens-bwalts Please review this pull request

**Comment by muffato** [comment]
Can you fill the PR template to explain what this is for ?

**Comment by mira13** [comment]
@muffato PR template is filled now

**Comment by muffato** [comment]
Still not very clear. What problem are you trying to solve ?

The output of beekeeper has changed. It doesn't print the list of analyses any more.

**Comment by mira13** [comment]
> On 7 Mar 2019, at 11:27, Matthieu Muffato <notifications@github.com> wrote:
> 
> Still not very clear. What problem are you trying to solve ?
> 
> 


Now we have many different types of output in code - direct printing, adding to hash and print late, and to warnings array,
So with formatter  and in code we have one way to print- using formatter. 
> The output of beekeeper has changed. It doesn't print the list of analyses any more.
> 
> 


This is a bug, will fix it and let you know

**Comment by muffato** [comment]
But currently, the Formatter is only used as a proxy to `print`. Do you plan to use the Formatter in more places / with more formats ?

BTW, indentation is 4 spaces, not 2 (in Queen.pm)

**Comment by mira13** [comment]
1.Current issue - to remove all prints from queen.pm is impossible to do without some wrapper. 
Because there is a custom print function for analysis, and if I just push all prints in one array and print after Queen.pm is finished,  either analysis will be not printed, if we comment this code or will be printed before all output.

In tweak_pipeline currently I have just commented custom output code.

2. Yes, every new format - means now new return variable, that also affects files that call the issued script.
And with formatter - only in issued script we add new code for new format, and formatter takes al care about printing.

**Pull request closed without merging**
